<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\PropertyImage;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      $user = User::first();
        $properties = [
            [
                'title' => 'Luxury Villa with Pool',
                'description' => 'Stunning modern villa featuring 5 spacious bedrooms, private swimming pool, beautiful garden, and premium finishes throughout. Located in prestigious BKK1 area.',
                'listing_type' => 'For Sale',
                'property_type' => 'Villa',
                'price' => 1250000,
                'location' => 'Street 240, BKK1',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'area' => 450,
                'features' => json_encode(['Swimming Pool', 'Garden', 'Parking', 'Security', 'Gym']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Modern Family Home',
                'description' => 'Perfect family residence with 4 bedrooms, open plan living areas, modern kitchen, and ample parking space. Great location near international schools.',
                'listing_type' => 'For Sale',
                'property_type' => 'House',
                'price' => 580000,
                'location' => 'Toul Kork',
                'city' => 'Phnom Penh',
                'district' => 'Toul Kork',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 280,
                'features' => json_encode(['Parking', 'Garden', 'Security']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Spacious Townhouse',
                'description' => 'Well-maintained townhouse in quiet residential area. Features 3 bedrooms, 2 bathrooms, balcony, and covered parking.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 420000,
                'location' => 'Chamkarmon',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 180,
                'features' => json_encode(['Parking', 'Security']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Executive Residence',
                'description' => 'Premium executive home with high-end finishes, spacious rooms, private pool, and beautiful landscaping. Perfect for families.',
                'listing_type' => 'For Sale',
                'property_type' => 'Villa',
                'price' => 950000,
                'location' => 'Daun Penh',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'area' => 380,
                'features' => json_encode(['Swimming Pool', 'Garden', 'Parking', 'Security', 'Gym', 'Sauna']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Contemporary Villa',
                'description' => 'Beautiful contemporary design villa with open spaces, natural lighting, and modern amenities. Includes pool and garden.',
                'listing_type' => 'For Sale',
                'property_type' => 'Villa',
                'price' => 720000,
                'location' => 'Sen Sok',
                'city' => 'Phnom Penh',
                'district' => 'Sen Sok',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 320,
                'features' => json_encode(['Swimming Pool', 'Garden', 'Parking', 'Security']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Luxury Penthouse',
                'description' => 'Stunning penthouse apartment with panoramic city views. Features 4 bedrooms, large terrace, premium fixtures, and parking.',
                'listing_type' => 'For Sale',
                'property_type' => 'Condo',
                'price' => 1850000,
                'location' => 'BKK1',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 4,
                'bathrooms' => 4,
                'area' => 380,
                'features' => json_encode(['Parking', 'Security', 'Gym', 'Swimming Pool']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Serviced Apartment',
                'description' => 'Fully furnished serviced apartment available for rent. Includes utilities, housekeeping, gym, and pool access.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 1800,
                'location' => 'BKK1',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 120,
                'features' => json_encode(['Parking', 'Security', 'Gym', 'Swimming Pool', 'WiFi']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Cozy Bungalow',
                'description' => 'Charming bungalow in peaceful neighborhood. Perfect for small families or professionals.',
                'listing_type' => 'For Sale',
                'property_type' => 'House',
                'price' => 350000,
                'location' => 'Toul Kork',
                'city' => 'Phnom Penh',
                'district' => 'Toul Kork',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 200,
                'features' => json_encode(['Parking', 'Garden']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Garden Villa',
                'description' => 'Spacious villa with large garden perfect for outdoor activities. Features modern design and quality construction.',
                'listing_type' => 'For Sale',
                'property_type' => 'Villa',
                'price' => 890000,
                'location' => 'Sen Sok',
                'city' => 'Phnom Penh',
                'district' => 'Sen Sok',
                'bedrooms' => 5,
                'bathrooms' => 3,
                'area' => 420,
                'features' => json_encode(['Garden', 'Parking', 'Security', 'Swimming Pool']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Modern Apartment',
                'description' => 'Contemporary apartment in central location. Close to shopping, restaurants, and public transport.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 950,
                'location' => 'Chamkarmon',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 85,
                'features' => json_encode(['Parking', 'Security', 'WiFi']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop']
            ],
            // Additional 40 properties
            [
                'title' => 'Premium Studio Loft',
                'description' => 'Stylish studio loft with high ceilings and modern fixtures. Perfect for young professionals.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 650,
                'location' => 'Russian Market',
                'city' => 'Phnom Penh',
                'district' => 'Toul Tompong',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'area' => 45,
                'features' => json_encode(['WiFi', 'Security', 'Elevator']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Riverside Duplex',
                'description' => 'Stunning duplex with river views. Two-level living with modern amenities and boat dock access.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 680000,
                'location' => 'Riverside',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 250,
                'features' => json_encode(['River View', 'Parking', 'Boat Dock', 'Terrace']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Colonial Style Mansion',
                'description' => 'Historic colonial mansion fully renovated with modern amenities. Large grounds and classic architecture.',
                'listing_type' => 'For Sale',
                'property_type' => 'Villa',
                'price' => 2500000,
                'location' => 'Independence Monument',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 7,
                'bathrooms' => 6,
                'area' => 850,
                'features' => json_encode(['Swimming Pool', 'Garden', 'Parking', 'Security', 'Wine Cellar', 'Library']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1566908829550-e6551b00979b?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Smart Home Condo',
                'description' => 'Ultra-modern condo with smart home technology. Voice-controlled lighting, climate, and security systems.',
                'listing_type' => 'For Sale',
                'property_type' => 'Condo',
                'price' => 450000,
                'location' => 'Diamond Island',
                'city' => 'Phnom Penh',
                'district' => 'Tonle Bassac',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 130,
                'features' => json_encode(['Smart Home', 'Parking', 'Gym', 'Swimming Pool']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Eco-Friendly House',
                'description' => 'Sustainable living home with solar panels, rainwater harvesting, and organic garden.',
                'listing_type' => 'For Sale',
                'property_type' => 'House',
                'price' => 520000,
                'location' => 'Boeng Keng Kang',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 220,
                'features' => json_encode(['Solar Panels', 'Garden', 'Parking', 'Rainwater System']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Boutique Shophouse',
                'description' => 'Prime commercial shophouse with living quarters above. Perfect for business with residence.',
                'listing_type' => 'For Sale',
                'property_type' => 'Commercial',
                'price' => 750000,
                'location' => 'Monivong Boulevard',
                'city' => 'Phnom Penh',
                'district' => '7 Makara',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 180,
                'features' => json_encode(['Commercial Space', 'Parking', 'Security']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Minimalist Flat',
                'description' => 'Clean, minimalist design flat with efficient use of space and natural light throughout.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 800,
                'location' => 'Street 51',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 65,
                'features' => json_encode(['Parking', 'Security', 'WiFi']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Lake View Villa',
                'description' => 'Spectacular villa overlooking Boeng Kak lake. Premium finishes and private jetty.',
                'listing_type' => 'For Sale',
                'property_type' => 'Villa',
                'price' => 1100000,
                'location' => 'Boeng Kak',
                'city' => 'Phnom Penh',
                'district' => 'Toul Kork',
                'bedrooms' => 6,
                'bathrooms' => 5,
                'area' => 520,
                'features' => json_encode(['Lake View', 'Swimming Pool', 'Garden', 'Jetty', 'Security']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Urban Loft Apartment',
                'description' => 'Industrial-style loft with exposed brick, high ceilings, and open floor plan.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 1200,
                'location' => 'Street 308',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 110,
                'features' => json_encode(['High Ceilings', 'Parking', 'Security']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Traditional Khmer House',
                'description' => 'Beautifully preserved traditional Khmer wooden house with modern upgrades.',
                'listing_type' => 'For Sale',
                'property_type' => 'House',
                'price' => 380000,
                'location' => 'Wat Phnom',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 4,
                'bathrooms' => 2,
                'area' => 280,
                'features' => json_encode(['Garden', 'Traditional Architecture', 'Parking']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Executive Penthouse',
                'description' => 'Top floor penthouse with 360-degree city views. Private elevator and rooftop terrace.',
                'listing_type' => 'For Rent',
                'property_type' => 'Condo',
                'price' => 3500,
                'location' => 'Naga World',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 320,
                'features' => json_encode(['City View', 'Private Elevator', 'Rooftop Terrace', 'Gym']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Garden Cottage',
                'description' => 'Charming cottage surrounded by lush gardens. Quiet and peaceful setting.',
                'listing_type' => 'For Sale',
                'property_type' => 'House',
                'price' => 280000,
                'location' => 'Khan Russey Keo',
                'city' => 'Phnom Penh',
                'district' => 'Russey Keo',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 150,
                'features' => json_encode(['Garden', 'Parking', 'Quiet Area']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Modern Townhouse Complex',
                'description' => 'Brand new townhouse in gated community with shared facilities and 24/7 security.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 485000,
                'location' => 'Street 271',
                'city' => 'Phnom Penh',
                'district' => 'Sen Sok',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 190,
                'features' => json_encode(['Gated Community', 'Playground', 'Security', 'Parking']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1599427303058-f04cbcf4756f?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Riverside Apartment',
                'description' => 'Beautiful apartment with Mekong river views. Walking distance to restaurants and cafes.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 1100,
                'location' => 'Sisowath Quay',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 95,
                'features' => json_encode(['River View', 'Security', 'WiFi']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1560448075-bb485b067938?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Luxury Pool Villa',
                'description' => 'Exclusive villa with infinity pool, home theater, and wine cellar. Ultimate luxury living.',
                'listing_type' => 'For Sale',
                'property_type' => 'Villa',
                'price' => 1750000,
                'location' => 'Boeng Tumpun',
                'city' => 'Phnom Penh',
                'district' => 'Mean Chey',
                'bedrooms' => 6,
                'bathrooms' => 6,
                'area' => 650,
                'features' => json_encode(['Infinity Pool', 'Home Theater', 'Wine Cellar', 'Gym', 'Security']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Student Studio',
                'description' => 'Affordable studio apartment near universities. Ideal for students and young professionals.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 350,
                'location' => 'Street 163',
                'city' => 'Phnom Penh',
                'district' => 'Toul Tompong',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'area' => 35,
                'features' => json_encode(['WiFi', 'Security']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Commercial Building',
                'description' => 'Multi-story commercial building suitable for offices or retail. Prime business location.',
                'listing_type' => 'For Sale',
                'property_type' => 'Commercial',
                'price' => 3200000,
                'location' => 'Preah Sihanouk Blvd',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 0,
                'bathrooms' => 8,
                'area' => 1200,
                'features' => json_encode(['Elevator', 'Parking', 'Generator', 'CCTV']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Compact Condo',
                'description' => 'Efficiently designed condo perfect for singles or couples. Great investment opportunity.',
                'listing_type' => 'For Sale',
                'property_type' => 'Condo',
                'price' => 185000,
                'location' => 'Olympic Stadium',
                'city' => 'Phnom Penh',
                'district' => '7 Makara',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 55,
                'features' => json_encode(['Swimming Pool', 'Gym', 'Security']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1565623006066-82f23c79210b?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Family Duplex',
                'description' => 'Spacious two-story duplex with private entrance and backyard. Family-friendly neighborhood.',
                'listing_type' => 'For Rent',
                'property_type' => 'Townhouse',
                'price' => 1400,
                'location' => 'Boeng Keng Kang 3',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 165,
                'features' => json_encode(['Garden', 'Parking', 'Security']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1602941525421-8f8b81d3edbb?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Boutique Villa',
                'description' => 'Architecturally stunning villa with unique design elements and premium materials throughout.',
                'listing_type' => 'For Sale',
                'property_type' => 'Villa',
                'price' => 980000,
                'location' => 'Toul Sleng',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 4,
                'bathrooms' => 4,
                'area' => 380,
                'features' => json_encode(['Swimming Pool', 'Designer Kitchen', 'Garden', 'Security']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Urban Flat Share',
                'description' => 'Modern flat with shared common areas. Perfect for young professionals seeking community.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 450,
                'location' => 'Street 278',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 40,
                'features' => json_encode(['Shared Kitchen', 'WiFi', 'Security']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Waterfront Mansion',
                'description' => 'Grand waterfront mansion with private beach access. Entertainment wing and guest quarters.',
                'listing_type' => 'For Sale',
                'property_type' => 'Villa',
                'price' => 3800000,
                'location' => 'Koh Pich',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 8,
                'bathrooms' => 8,
                'area' => 980,
                'features' => json_encode(['Beach Access', 'Swimming Pool', 'Tennis Court', 'Guest House', 'Security']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Artistic Loft',
                'description' => 'Creative space with artist studio, large windows, and unique architectural features.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 950,
                'location' => 'Street 240½',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 90,
                'features' => json_encode(['Studio Space', 'High Ceilings', 'Natural Light']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Corner Shophouse',
                'description' => 'Strategic corner location shophouse with excellent visibility and foot traffic.',
                'listing_type' => 'For Sale',
                'property_type' => 'Commercial',
                'price' => 920000,
                'location' => 'Central Market',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 210,
                'features' => json_encode(['Corner Location', 'Commercial Space', 'Storage']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1580216643062-cf460548a66a?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Green Bungalow',
                'description' => 'Eco-conscious bungalow with sustainable features and organic vegetable garden.',
                'listing_type' => 'For Rent',
                'property_type' => 'House',
                'price' => 850,
                'location' => 'Chroy Changvar',
                'city' => 'Phnom Penh',
                'district' => 'Chroy Changvar',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 140,
                'features' => json_encode(['Solar Power', 'Vegetable Garden', 'Parking']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Sky Villa',
                'description' => 'Exclusive sky villa on top floors with private pool and panoramic views.',
                'listing_type' => 'For Sale',
                'property_type' => 'Condo',
                'price' => 2200000,
                'location' => 'Exchange Square',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 4,
                'bathrooms' => 5,
                'area' => 450,
                'features' => json_encode(['Sky Pool', 'Private Lift', 'Smart Home', 'Wine Bar']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Riverside Cottage',
                'description' => 'Quaint cottage along the riverside with beautiful sunset views and private garden.',
                'listing_type' => 'For Sale',
                'property_type' => 'House',
                'price' => 320000,
                'location' => 'Prek Pnov',
                'city' => 'Phnom Penh',
                'district' => 'Prek Pnov',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 130,
                'features' => json_encode(['River View', 'Garden', 'Dock Access']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Modern Office Space',
                'description' => 'Contemporary office space with open floor plan, meeting rooms, and parking.',
                'listing_type' => 'For Rent',
                'property_type' => 'Commercial',
                'price' => 2800,
                'location' => 'Norodom Blvd',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 0,
                'bathrooms' => 3,
                'area' => 320,
                'features' => json_encode(['Meeting Rooms', 'Parking', 'Reception Area', 'Pantry']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Furnished Studio',
                'description' => 'Fully furnished studio with modern appliances and stylish decor. Move-in ready.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 550,
                'location' => 'Street 360',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'area' => 40,
                'features' => json_encode(['Fully Furnished', 'WiFi', 'Cable TV']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Classic Colonial House',
                'description' => 'Restored colonial house with period features and modern conveniences.',
                'listing_type' => 'For Sale',
                'property_type' => 'House',
                'price' => 680000,
                'location' => 'Street 96',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 5,
                'bathrooms' => 3,
                'area' => 350,
                'features' => json_encode(['Heritage Features', 'Garden', 'Parking', 'High Ceilings']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Rooftop Apartment',
                'description' => 'Top floor apartment with private rooftop terrace and BBQ area.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 1250,
                'location' => 'Street 63',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 110,
                'features' => json_encode(['Rooftop Terrace', 'BBQ Area', 'City Views']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Investment Condo',
                'description' => 'High-yield investment condo in prime location with rental management available.',
                'listing_type' => 'For Sale',
                'property_type' => 'Condo',
                'price' => 280000,
                'location' => 'Toul Tompong',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 75,
                'features' => json_encode(['Pool', 'Gym', 'Management Service']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Garden Townhouse',
                'description' => 'Corner townhouse with wraparound garden and outdoor entertainment area.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 520000,
                'location' => 'Boeng Trabek',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 200,
                'features' => json_encode(['Corner Unit', 'Garden', 'BBQ Area', 'Parking']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1464146072230-91cabc968266?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Embassy Quarter Villa',
                'description' => 'Diplomatic area villa with high security, elegant design, and entertainment spaces.',
                'listing_type' => 'For Rent',
                'property_type' => 'Villa',
                'price' => 3800,
                'location' => 'Embassy Quarter',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 5,
                'bathrooms' => 5,
                'area' => 480,
                'features' => json_encode(['High Security', 'Swimming Pool', 'Maid Quarters', 'Generator']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Modern Flat Complex',
                'description' => 'New development flat with shared rooftop pool and co-working space.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 650,
                'location' => 'Street 598',
                'city' => 'Phnom Penh',
                'district' => 'Sen Sok',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 58,
                'features' => json_encode(['Rooftop Pool', 'Co-working Space', 'Gym']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Lakefront Property',
                'description' => 'Rare lakefront property with private beach and boat house. Serene location.',
                'listing_type' => 'For Sale',
                'property_type' => 'House',
                'price' => 890000,
                'location' => 'Boeng Cheung Ek',
                'city' => 'Phnom Penh',
                'district' => 'Mean Chey',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 380,
                'features' => json_encode(['Lake Access', 'Private Beach', 'Boat House', 'Garden']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Hip District Loft',
                'description' => 'Trendy loft in artistic district with cafes, galleries, and nightlife nearby.',
                'listing_type' => 'For Rent',
                'property_type' => 'Apartment',
                'price' => 850,
                'location' => 'Street 172',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 75,
                'features' => json_encode(['Open Plan', 'Exposed Brick', 'Balcony']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1515263487990-61b07816b324?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Prime Retail Space',
                'description' => 'High-traffic retail space perfect for flagship store or showroom.',
                'listing_type' => 'For Rent',
                'property_type' => 'Commercial',
                'price' => 4500,
                'location' => 'Monivong Blvd',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'area' => 450,
                'features' => json_encode(['Street Frontage', 'Display Windows', 'Storage', 'Loading Bay']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Suburban Family Home',
                'description' => 'Perfect suburban home with large yard, quiet street, and family-friendly neighborhood.',
                'listing_type' => 'For Sale',
                'property_type' => 'House',
                'price' => 420000,
                'location' => 'Kilometer 6',
                'city' => 'Phnom Penh',
                'district' => 'Russey Keo',
                'bedrooms' => 4,
                'bathrooms' => 2,
                'area' => 240,
                'features' => json_encode(['Large Yard', 'Garage', 'Quiet Street']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Prime Development Land with Villa in BKK1',
                'description' => 'Exceptional 800sqm property with existing villa in the heart of BKK1. Current structure can be renovated or demolished for new development. Clear hard title, corner plot with dual road access.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 2800000,
                'location' => 'Street 306, BKK1',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 800,
                'features' => json_encode(['Corner Plot', 'Hard Title', 'Dual Access', 'Prime Location', 'Commercial Zone']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Waterfront Land with House on Diamond Island',
                'description' => 'Rare 1,200sqm waterfront property with existing house on prestigious Diamond Island. Stunning river views, perfect for renovation or redevelopment. Soft title with conversion possibility.',
                'listing_type' => 'For Sale',
                'property_type' => 'Commercial',
                'price' => 3600000,
                'location' => 'Koh Pich (Diamond Island)',
                'city' => 'Phnom Penh',
                'district' => 'Tonle Bassac',
                'bedrooms' => 3,
                'bathrooms' => 4,
                'area' => 1200,
                'features' => json_encode(['Waterfront', 'River Views', 'Prestigious Location', 'Development Ready']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1621619856624-42fd193a0661?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Commercial Land with Shophouse Near Russian Market',
                'description' => 'Strategic 500sqm plot with existing shophouse near bustling Russian Market area. High foot traffic location ideal for business or redevelopment. Hard title available.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 950000,
                'location' => 'Street 440, Russian Market',
                'city' => 'Phnom Penh',
                'district' => 'Toul Tom Poung',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 500,
                'features' => json_encode(['Commercial Area', 'High Traffic', 'Hard Title', 'Near Market']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Large Development Land with Farmhouse in Sen Sok',
                'description' => '5 hectares of prime development land with existing structures in rapidly growing Sen Sok district. Perfect for borey development or mixed-use project. Near Ring Road 3.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 4500000,
                'location' => 'National Road 5, Sen Sok',
                'city' => 'Phnom Penh',
                'district' => 'Sen Sok',
                'bedrooms' => 4,
                'bathrooms' => 4,
                'area' => 50000,
                'features' => json_encode(['Large Plot', 'Development Zone', 'Near Ring Road', 'Investment Opportunity']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Beachfront Land with Villa in Sihanoukville',
                'description' => 'Pristine 2,000sqm beachfront property with existing beach villa on Otres Beach. Perfect for renovation or resort development. Direct beach access with stunning sunset views.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 1800000,
                'location' => 'Otres Beach',
                'city' => 'Sihanoukville',
                'district' => 'Mittapheap',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 2000,
                'features' => json_encode(['Beachfront', 'Tourism Zone', 'Sunset Views', 'Resort Potential']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Agricultural Land with Farm Villa',
                'description' => '10,000sqm agricultural land with existing farm villa in Kandal province, 15 minutes from Phnom Penh. Suitable for eco-resort development or private estate.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 350000,
                'location' => 'Ta Khmao',
                'city' => 'Kandal',
                'district' => 'Ta Khmao',
                'bedrooms' => 2,
                'bathrooms' => 3,
                'area' => 10000,
                'features' => json_encode(['Agricultural', 'Near Capital', 'Eco-Tourism Potential', 'Peaceful Location']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1540202403-b7abd6747a18?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Embassy Quarter Land with Colonial Villa',
                'description' => 'Exclusive 600sqm plot with charming colonial villa in embassy district, BKK3. Surrounded by embassies and high-end residences. Perfect for renovation or redevelopment.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 2100000,
                'location' => 'Street 70, BKK3',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 4,
                'bathrooms' => 2,
                'area' => 600,
                'features' => json_encode(['Embassy Area', 'Prestigious', 'Security', 'Quiet Street', 'Hard Title']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Riverside Land with Khmer House in Chroy Changvar',
                'description' => '3,000sqm riverside plot with traditional Khmer house overlooking Mekong River. Ideal for luxury resort or residential redevelopment. Growing area with new infrastructure.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 2400000,
                'location' => 'Chroy Changvar Bridge Area',
                'city' => 'Phnom Penh',
                'district' => 'Chroy Changvar',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 3000,
                'features' => json_encode(['Riverside', 'Mekong Views', 'Development Area', 'Bridge Access']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1516156008625-3a9d6067fab5?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Corner Land with Townhouse in Toul Kork',
                'description' => 'Well-positioned 450sqm corner plot with modern townhouse in developing Toul Kork area. Near schools, hospitals, and shopping. Ready for immediate occupancy or redevelopment.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 675000,
                'location' => 'Street 289, Toul Kork',
                'city' => 'Phnom Penh',
                'district' => 'Toul Kork',
                'bedrooms' => 2,
                'bathrooms' => 4,
                'area' => 450,
                'features' => json_encode(['Corner Plot', 'Near Schools', 'Residential Zone', 'Good Access']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1494526585095-c41746248156?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Industrial Land with Warehouse Near Airport',
                'description' => '2 hectares industrial land with existing warehouse structure near Phnom Penh International Airport. Perfect for logistics center or manufacturing. All utilities available.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 1600000,
                'location' => 'Russian Boulevard',
                'city' => 'Phnom Penh',
                'district' => 'Dangkor',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 20000,
                'features' => json_encode(['Industrial Zone', 'Near Airport', 'Utilities Ready', 'Logistics Hub']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Boutique Land with Colonial Building in Kampot',
                'description' => '800sqm riverside plot with charming colonial building in Kampot town. Tourism area perfect for boutique hotel conversion or restaurant. Heritage charm with modern potential.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 320000,
                'location' => 'Riverside Road',
                'city' => 'Kampot',
                'district' => 'Kampot',
                'bedrooms' => 3,
                'bathrooms' => 4,
                'area' => 800,
                'features' => json_encode(['Riverside', 'Tourism Area', 'Colonial Quarter', 'Restaurant Potential']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Mountain View Land with Sea View Villa in Kep',
                'description' => '5,000sqm hillside land with luxury villa offering panoramic sea and mountain views in Kep. Near National Park, ideal for boutique resort or private estate.',
                'listing_type' => 'For Sale',
                'property_type' => 'Land',
                'price' => 750000,
                'location' => 'Kep Hillside',
                'city' => 'Kep',
                'district' => 'Kep',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 5000,
                'features' => json_encode(['Sea Views', 'Mountain Views', 'Near National Park', 'Tourism Zone']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Prime Office Building in BKK1 Business District',
                'description' => 'Modern 6-story office building with 2,500sqm total floor area in BKK1 CBD. Currently 85% occupied with stable rental income. Ground floor retail space, ample parking, and excellent corporate tenant mix.',
                'listing_type' => 'For Sale',
                'property_type' => 'Commercial',
                'price' => 5800000,
                'location' => 'Sothearos Boulevard, BKK1',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 3,
                'bathrooms' => 5,
                'area' => 2500,
                'features' => json_encode(['Elevator', 'Parking Space', 'Security 24/7', 'Central Location', 'High ROI', 'Backup Generator']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Boutique Hotel Near Russian Market',
                'description' => '28-room boutique hotel in prime tourist area near Russian Market. Fully operational with restaurant, rooftop bar, and spa. Excellent TripAdvisor ratings and established clientele. Turnkey investment opportunity.',
                'listing_type' => 'For Sale',
                'property_type' => 'Commercial',
                'price' => 3200000,
                'location' => 'Street 450, Toul Tom Poung',
                'city' => 'Phnom Penh',
                'district' => 'Toul Tom Poung',
                'bedrooms' => 3,
                'bathrooms' => 5,
                'area' => 1800,
                'features' => json_encode(['Restaurant', 'Rooftop Bar', 'Spa', 'Fully Furnished', 'Operating Business', 'Tourist Area']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Retail Shopping Complex on Monivong Boulevard',
                'description' => 'Three-story retail complex with 15 shop units on busy Monivong Boulevard. High foot traffic location with established tenants including banks, cafes, and retail stores. Parking for 50 vehicles.',
                'listing_type' => 'For Sale',
                'property_type' => 'Commercial',
                'price' => 4500000,
                'location' => 'Monivong Boulevard',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 3,
                'bathrooms' => 6,
                'area' => 3200,
                'features' => json_encode(['Multiple Units', 'High Traffic', 'Parking Lot', 'Established Tenants', 'Main Road', 'Investment Property']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1555636222-cae831e670b3?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Modern Warehouse Near Phnom Penh Port',
                'description' => 'Large 4,000sqm warehouse facility with office space near Phnom Penh Autonomous Port. High ceilings, loading docks, 24/7 security. Ideal for logistics, distribution, or light manufacturing.',
                'listing_type' => 'For Sale',
                'property_type' => 'Commercial',
                'price' => 2800000,
                'location' => 'Street 217, Dangkor',
                'city' => 'Phnom Penh',
                'district' => 'Dangkor',
                'bedrooms' => 2,
                'bathrooms' => 4,
                'area' => 4000,
                'features' => json_encode(['Loading Docks', 'High Ceilings', 'Office Space', 'Security System', 'Near Port', 'Industrial Zone']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Mixed-Use Building in Riverside Tourist Quarter',
                'description' => 'Prime riverside location with restaurant on ground floor, guesthouse rooms above, and rooftop bar with Mekong views. Fully licensed and operational. Perfect for hospitality investment in tourist hotspot.',
                'listing_type' => 'For Sale',
                'property_type' => 'Commercial',
                'price' => 2400000,
                'location' => 'Sisowath Quay',
                'city' => 'Phnom Penh',
                'district' => 'Daun Penh',
                'bedrooms' => 3,
                'bathrooms' => 5,
                'area' => 850,
                'features' => json_encode(['Riverside', 'Restaurant', 'Guesthouse', 'Rooftop Bar', 'Tourist Area', 'River Views']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop']
            ],

            [
                'title' => 'Modern Corner Townhouse in Borey Peng Huoth',
                'description' => 'Beautiful 3-story corner townhouse in prestigious gated community. Features 4 spacious bedrooms, modern kitchen with island, private rooftop terrace, and covered parking for 2 cars. 24/7 security and community amenities.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 285000,
                'location' => 'Borey Peng Huoth, Street 371',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 220,
                'features' => json_encode(['Corner Unit', 'Rooftop Terrace', 'Gated Community', 'Swimming Pool Access', 'Parking', 'Security 24/7']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Luxury Twin Villa Near Aeon Mall',
                'description' => 'Stunning twin villa townhouse with contemporary design near Aeon Mall Sen Sok. 3 bedrooms with walk-in closets, open-plan living area, private garden, and smart home features. Perfect for modern families.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 195000,
                'location' => 'Borey Chip Mong Sen Sok',
                'city' => 'Phnom Penh',
                'district' => 'Sen Sok',
                'bedrooms' => 3,
                'bathrooms' => 4,
                'area' => 180,
                'features' => json_encode(['Near Mall', 'Private Garden', 'Smart Home', 'Modern Design', 'Parking']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Renovated Shophouse Townhouse in BKK3',
                'description' => 'Beautifully renovated 4-story shophouse converted to modern townhouse. Ground floor suitable for home office, 3 bedrooms upstairs, rooftop entertainment area with city views. Prime BKK3 location.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 520000,
                'location' => 'Street 63, BKK3',
                'city' => 'Phnom Penh',
                'district' => 'Chamkarmon',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 240,
                'features' => json_encode(['Home Office', 'Rooftop', 'City Views', 'Renovated', 'Prime Location']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Family Townhouse in Toul Kork',
                'description' => 'Spacious 2-story townhouse in quiet residential area. Features large living spaces, 4 bedrooms perfect for growing families, maid room, covered parking, and small garden. Close to TK Avenue and schools.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 165000,
                'location' => 'Street 315, Toul Kork',
                'city' => 'Phnom Penh',
                'district' => 'Toul Kork',
                'bedrooms' => 4,
                'bathrooms' => 2,
                'area' => 150,
                'features' => json_encode(['Maid Room', 'Near Schools', 'Quiet Area', 'Garden', 'Parking']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Executive Townhouse in Diamond Island',
                'description' => 'Premium 3-story townhouse in exclusive Diamond Island development. High-end finishes, 3 bedrooms with ensuite bathrooms, European kitchen, private elevator, and underground parking. Walking distance to Elite Golf Club.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 680000,
                'location' => 'Koh Pich (Diamond Island)',
                'city' => 'Phnom Penh',
                'district' => 'Tonle Bassac',
                'bedrooms' => 3,
                'bathrooms' => 4,
                'area' => 280,
                'features' => json_encode(['Private Elevator', 'Premium Finishes', 'Golf Club Access', 'Underground Parking', 'River Views']),
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Affordable Townhouse in Chbar Ampov',
                'description' => 'Well-maintained budget-friendly townhouse in developing Chbar Ampov district. 2 spacious bedrooms, open living area, basic kitchen, and space for motorbike parking. Great starter home near National Road 1.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 85000,
                'location' => 'Borey Piphup Thmey',
                'city' => 'Phnom Penh',
                'district' => 'Chbar Ampov',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 120,
                'features' => json_encode(['Affordable', 'Near Highway', 'Developing Area', 'Parking']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Riverside Townhouse in Chroy Changvar',
                'description' => 'Contemporary 3-bedroom townhouse with Mekong River views. Features modern open-plan design, quality fixtures, balconies on each floor, and rooftop terrace. Part of new riverside community development.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 235000,
                'location' => 'Chroy Changvar Riverside',
                'city' => 'Phnom Penh',
                'district' => 'Chroy Changvar',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 190,
                'features' => json_encode(['River Views', 'Multiple Balconies', 'Rooftop Terrace', 'Modern Design', 'New Development']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop']
            ],
            [
                'title' => 'Garden Townhouse in Borey Vimean Phnom Penh',
                'description' => 'Charming townhouse in established borey with mature gardens. 3 bedrooms, spacious living areas, covered carport, and private backyard perfect for family gatherings. Community playground and 24-hour security.',
                'listing_type' => 'For Sale',
                'property_type' => 'Townhouse',
                'price' => 178000,
                'location' => 'Borey Vimean Phnom Penh, Street 1986',
                'city' => 'Phnom Penh',
                'district' => 'Dangkor',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 160,
                'features' => json_encode(['Private Garden', 'Playground', 'Gated Community', 'Established Area', 'Security']),
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop']
            ],
        ];


        foreach ($properties as $propertyData) {
            $images = $propertyData['images'];
            unset($propertyData['images']);

            $property = Property::create(array_merge($propertyData, ['user_id' => $user->id]));

            // Add translations for all languages
            $locales = ['en', 'km', 'zh', 'fr'];

            // Translation mappings for translatable fields
            $translations = [
                'en' => [
                    'title' => $propertyData['title'],
                    'description' => $propertyData['description'],
                    'location' => $propertyData['location'],
                    'district' => $propertyData['district'],
                    'features' => $propertyData['features'],
                ],
                'km' => [
                    'title' => $propertyData['title'] . ' (KM)',
                    'description' => $propertyData['description'] . ' [ការពិពណ៌នាជាភាសាខ្មែរ]',
                    'location' => $propertyData['location'],
                    'district' => $propertyData['district'],
                    'features' => $propertyData['features'],
                ],
                'zh' => [
                    'title' => $propertyData['title'] . ' (中文)',
                    'description' => $propertyData['description'] . ' [中文描述]',
                    'location' => $propertyData['location'],
                    'district' => $propertyData['district'],
                    'features' => $propertyData['features'],
                ],
                'fr' => [
                    'title' => $propertyData['title'] . ' (FR)',
                    'description' => $propertyData['description'] . ' [Description en français]',
                    'location' => $propertyData['location'],
                    'district' => $propertyData['district'],
                    'features' => $propertyData['features'],
                ],
            ];

            // Set translations for each locale
            foreach ($locales as $locale) {
                if (isset($translations[$locale])) {
                    foreach ($translations[$locale] as $field => $value) {
                        $property->setTranslation($field, $value, $locale);
                    }
                }
            }

            // Add images
            foreach ($images as $index => $imageUrl) {
                PropertyImage::create([
                    'property_id' => $property->id,
                    'url' => $imageUrl,
                    'is_primary' => $index === 0,
                    'order' => $index,
                ]);
            }
        }

        $this->command->info('Properties seeded successfully with translations!');
    }
}
